version: '3.8'

services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:${TAG}
    networks:
      - traefik-public
    environment:
      - NODE_ENV=production
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        
        # Service - Port 3000 pour Next.js
        - "traefik.http.services.frontend-${ENV}.loadbalancer.server.port=3000"
        
        # HTTPS Router
        - "traefik.http.routers.frontend-${ENV}-secure.rule=Host(`actionuniversalfab.com`) || Host(`www.actionuniversalfab.com`)"
        - "traefik.http.routers.frontend-${ENV}-secure.entrypoints=websecure"
        - "traefik.http.routers.frontend-${ENV}-secure.tls=true"
        - "traefik.http.routers.frontend-${ENV}-secure.tls.certresolver=leresolver"
        - "traefik.http.routers.frontend-${ENV}-secure.service=frontend-${ENV}"
        
        # HTTP Router avec redirection
        - "traefik.http.routers.frontend-${ENV}-http.rule=Host(`actionuniversalfab.com`) || Host(`www.actionuniversalfab.com`)"
        - "traefik.http.routers.frontend-${ENV}-http.entrypoints=web"
        - "traefik.http.routers.frontend-${ENV}-http.middlewares=redirect-to-https"
        
        # Middleware redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  traefik-public:
    external: true