name: Deploy Frontend

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables based on branch
        id: vars
        run: |
          if [ "${GITHUB_REF##*/}" == "main" ]; then
            echo "ENV=production" >> $GITHUB_ENV
            echo "TAG=latest" >> $GITHUB_ENV
            echo "DOMAIN=actionuniversalfab.com" >> $GITHUB_ENV
            echo "REMOTE_PATH=/srv/frontend/main" >> $GITHUB_ENV
          else
            echo "ENV=staging" >> $GITHUB_ENV
            echo "TAG=staging" >> $GITHUB_ENV
            echo "DOMAIN=staging-client.actionuniversalfab.com" >> $GITHUB_ENV
            echo "REMOTE_PATH=/srv/frontend/staging" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ env.TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ env.TAG }}

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "${{ env.REMOTE_PATH }}"
          strip_components: 0

      - name: Deploy Frontend on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            cd ${{ env.REMOTE_PATH }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ env.TAG }}
            
            # Variables de d√©ploiement
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            export TAG=${{ env.TAG }}
            export ENV=${{ env.ENV }}
            export DOMAIN=${{ env.DOMAIN }}
            
            docker stack deploy -c docker-compose.yml frontend-${{ env.ENV }} --with-registry-auth
            docker image prune -f